/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classe;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Fentre extends javax.swing.JFrame {
    ArrayList<vechicule> vechicules;
    DefaultListModel modeleliste;
    File fichier;
    FileWriter fw;
    PrintWriter pw;

    /**
     * Creates new form Fentre
     */
    public Fentre() {
        initComponents();
        vechicules = new ArrayList<>();
        modeleliste= new DefaultListModel();
        try {
            fichier = new File("fichier.veh");
            fw = new FileWriter(fichier);
            pw = new PrintWriter(fw);

        } catch (IOException ex) {
                  ex.printStackTrace();
        }
        
        
        
        
        
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listevechicule = new javax.swing.JList<>();
        btnAjouter = new javax.swing.JButton();
        btnASuprimer = new javax.swing.JButton();
        btnAFermer = new javax.swing.JButton();
        btnenregistrer = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(listevechicule);

        btnAjouter.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        btnASuprimer.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnASuprimer.setText("Suprimer");
        btnASuprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnASuprimerActionPerformed(evt);
            }
        });

        btnAFermer.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAFermer.setText("Fermer");
        btnAFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAFermerActionPerformed(evt);
            }
        });

        btnenregistrer.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnenregistrer.setText("enregistrer");
        btnenregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenregistrerActionPerformed(evt);
            }
        });

        btnModifier.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnModifier.setText("Modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAjouter)
                        .addGap(37, 37, 37)
                        .addComponent(btnASuprimer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnModifier)
                        .addGap(28, 28, 28)
                        .addComponent(btnenregistrer)
                        .addGap(28, 28, 28)
                        .addComponent(btnAFermer)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAFermer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnenregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnASuprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnASuprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnASuprimerActionPerformed
        // TODO add your handling code here:
        if(listevechicule.isSelectionEmpty())
            JOptionPane.showMessageDialog(this, "selectioner un vechicule a suprimer","Pas de selection",
                    JOptionPane.ERROR);
        else{
        int indice = listevechicule.getSelectedIndex();
        modeleliste.remove(indice);
        vechicules.remove(indice);
        }
    }//GEN-LAST:event_btnASuprimerActionPerformed

    private void btnenregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenregistrerActionPerformed
        // TODO add your handling code here:
        for(vechicule v: vechicules){
            pw.println(v);
        }
        pw.close();
    }//GEN-LAST:event_btnenregistrerActionPerformed

    private void btnAFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAFermerActionPerformed
        // TODO add your handling code here:
        int chois=JOptionPane.showConfirmDialog(this, "tu est sur de sortir", "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(chois==0){System.exit(0);}
    }//GEN-LAST:event_btnAFermerActionPerformed

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        // TODO add your handling code here:
        
        vechicule v = null;
        String marque,modele,imatriculation,type;
        int nombreduporte,vitesseMAX;
        boolean remorque;
        type = JOptionPane.showInputDialog(this, "ENTRER LA TYPE DE VECHICULE VOITURE/CAMION/MOTO",JOptionPane.PLAIN_MESSAGE);
        if(type==null){}
        else if(type.equalsIgnoreCase("Voiture")){
            marque = JOptionPane.showInputDialog(this, "ENTRER LA MARQUE DE VECHICULE",JOptionPane.PLAIN_MESSAGE);
            modele = JOptionPane.showInputDialog(this, "ENTRER LE MODELE DE VECHICULE",JOptionPane.PLAIN_MESSAGE);
            imatriculation = JOptionPane.showInputDialog(this, "ENTRER L' IMATRICULATION DE VECHICULE",JOptionPane.PLAIN_MESSAGE);
            nombreduporte =Integer.parseInt(JOptionPane.showInputDialog(this, "ENTRER LE NOMBRE DU PORTE DE VOITURE",JOptionPane.PLAIN_MESSAGE) );
            v=new voiture(marque,modele,imatriculation,nombreduporte);
            vechicules.add(v);
        }
        else if(type.equalsIgnoreCase("MOTO")){
        marque = JOptionPane.showInputDialog(this, "ENTRER LA MARQUE DE VECHICULE",JOptionPane.PLAIN_MESSAGE);
        modele = JOptionPane.showInputDialog(this, "ENTRER LE MODELE DE VECHICULE",JOptionPane.PLAIN_MESSAGE);
        imatriculation = JOptionPane.showInputDialog(this, "ENTRER L' IMATRICULATION DE VECHICULE",JOptionPane.PLAIN_MESSAGE);
        vitesseMAX =Integer.parseInt(JOptionPane.showInputDialog(this, "ENTRER LE VITESSE MAX",JOptionPane.PLAIN_MESSAGE) );
        v= new motor(marque,modele,imatriculation,vitesseMAX);
                    vechicules.add(v);


        }
        else if (type.equalsIgnoreCase("camion")){
            marque = JOptionPane.showInputDialog(this, "ENTRER LA MARQUE DE VECHICULE",JOptionPane.PLAIN_MESSAGE);
            modele = JOptionPane.showInputDialog(this, "ENTRER LE MODELE DE VECHICULE",JOptionPane.PLAIN_MESSAGE);
            imatriculation = JOptionPane.showInputDialog(this, "ENTRER L' IMATRICULATION DE VECHICULE",JOptionPane.PLAIN_MESSAGE);
            int choix = JOptionPane.showConfirmDialog(this, "le camione a un remorque","remorque", JOptionPane.YES_NO_OPTION);
            if(choix==0)remorque=true;
            else remorque=false;
            v= new camion(marque,modele,imatriculation,remorque);
            vechicules.add(v);


        }
        else{
        JOptionPane.showMessageDialog(this, "votre chois est incorrecte", "choix incorrecte", JOptionPane.OK_OPTION);
        }
        modeleliste.add(modeleliste.getSize(),v);
        listevechicule.setModel(modeleliste);
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        // TODO add your handling code here:
        String model,marque,immatriculation;
        int nombreporte,vitesseMAX,remorque;
        if(listevechicule.isSelectionEmpty())
            JOptionPane.showMessageDialog(this, "selectioner un vechicule a modifier","Pas de selection",
                    JOptionPane.ERROR);
        else{
        int indice = listevechicule.getSelectedIndex();
        vechicule v= vechicules.get(indice);
        marque = JOptionPane.showInputDialog(this, "changer la marque", v.getMarque());
        v.setMarque(marque);
        model = JOptionPane.showInputDialog(this, "changer le model", v.getModele());
        v.setModele(model);
        immatriculation = JOptionPane.showInputDialog(this, "change la matricule", v.getImatriculation());
        v.setImatriculation(immatriculation);
        if(v instanceof voiture){
            nombreporte = Integer.valueOf(JOptionPane.showInputDialog(this, "entrer le nombre de porte de voiure", ((voiture) v).getNombrePorte() ));
            ((voiture) v).setNombrePorte(nombreporte);
        }
        else if(v instanceof motor){
        vitesseMAX = Integer.valueOf(JOptionPane.showInputDialog(this, "entrer la vitesse maximal", ((motor) v).getVitesseMax()));
        ((motor) v).setVitesseMax(vitesseMAX);
        }
        else if(v instanceof camion){
            remorque = JOptionPane.showConfirmDialog(this, "le camion a t'il un remorqe", "Remorque", JOptionPane.YES_NO_OPTION);
            boolean choix = true;
            if(remorque==JOptionPane.NO_OPTION){
            choix = false;
            }
            ((camion) v).setRemorque(choix);
        }
        else {
        JOptionPane.showConfirmDialog(this, "tu as fait un EREUR", "EREUR", JOptionPane.ERROR_MESSAGE);
        }
        }
        listevechicule.setModel(modeleliste);
    }//GEN-LAST:event_btnModifierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fentre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fentre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fentre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fentre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Fentre f = new Fentre() ;
                f.setVisible(true);
                f.setTitle("Gestion de parking");
                f.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAFermer;
    private javax.swing.JButton btnASuprimer;
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnenregistrer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listevechicule;
    // End of variables declaration//GEN-END:variables
}
